# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'learnredux' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  # Pods for learnredux
  pod 'React', :path => '../node_modules/react-native'
  target 'learnreduxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
